import type { Command } from 'commander';
import { agentOrchestrator } from '../orchestration/index.js';
import { runCommand } from './run-command.js';

export function registerPowCommand(program: Command): void {
  program
    .command('pow')
    .description('Show proof-of-work generated by the contribution agent')
    .action(() => runCommand('OpenMeta PoW', () => agentOrchestrator.showProofOfWork()));
}
